name: Rust

on:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --verbose

      - name: Lint with Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings
      - name: Download model for tests
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --example download --release
      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

      - name: Run Audit
        uses: actions-rs/cargo@v1
        with:
          command: audit
          args: -D warnings -f ./Cargo.lock

      # Verify that Readme.md is up to date.
      # - name: Make sure, Readme generated from lib.rs matches actual Readme
      #   if: matrix.os == 'ubuntu-latest'
      #   shell: bash
      #   working-directory: ./safetensors
      #   run: cargo readme > must_match_readme.md && diff must_match_readme.md README.md && diff must_match_readme.md ../README.md
